name: dc_selfcare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  cloud_firestore: ^4.13.6
  device_preview: ^1.1.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.6
  fluttertoast: ^8.2.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  riverpod_generator: ^2.3.3
  riverpod_annotation: ^2.2.0
  sizer: ^2.0.15
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  settings_ui: ^2.0.2
  skeleton_text: ^3.0.1
  modal_bottom_sheet: ^3.0.0-pre
  toggle_switch: ^2.1.0
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.6.18+2
  flutter_datetime_picker_plus: ^2.1.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0


dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/privacy_policy/ja.md
  # generate: true

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_icon.png'